# Generated by Django 3.1.7 on 2021-05-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ecommerceuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
